name: Ganother World Build Validation
on: [push]

jobs:
  build:
    strategy:
      matrix:
        go-version: [8.x, 10.x, 12.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - run: make test
      - run: make build-cross
